monolog:
  channels:
    - messaging
    - locking
    - events

  handlers:
    messaging:
      type: stream
      path: '%kernel.logs_dir%/messaging.log'
      level: debug
      channels: ['messaging']

    locking:
      type: stream
      path: '%kernel.logs_dir%/locking.log'
      level: debug
      channels: ['locking']

    events:
        type: stream
        path: '%kernel.logs_dir%/events.log'
        level: debug
        channels: ['events']
