services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    stdin_open: true
    tty: true

    volumes:
      - ../public:/usr/share/nginx/html/

  php:
    container_name: php
    build:
      context: php
      dockerfile: Dockerfile.dev

    env_file:
      - mariadb/envVars.public
      - elasticsearch/envVars.public
      - php/envVars.public
      - php/envVars.dev.public

    ports:
      - "9000:9000"

    stdin_open: true
    tty: true

    volumes:
      - ..:/var/www

    secrets:
      - app_secrets

  mariadb:
    container_name: db
    build:
      context: mariadb
      dockerfile: Dockerfile

    env_file:
      - mariadb/envVars.public

    ports:
      - "3380:3306"

    stdin_open: true
    tty: true

    volumes:
      - mariadb-data:/var/lib/mariadb

    secrets:
      - mariadb_password
      - mariadb_root_password

    environment:
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password

  elasticsearch:
    container_name: elasticsearch

    image: elasticsearch:9.0.3

    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

    ports:
      - "9200:9200"
      - "9300:9300"

    stdin_open: true
    tty: true

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  elasticsearch-data:
  mariadb-data:

secrets:
  app_secrets:
    file: php/appEnvVars.private
  mariadb_password:
    file: mariadb/mariadb_password_file.private
  mariadb_root_password:
    file: mariadb/mariadb_root_password_file.private
  elasticsearch_password:
    file: elasticsearch/elasticsearch_password_file.private
