services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    stdin_open: true
    tty: true

    volumes:
      - ../public:/usr/share/nginx/html/

    extra_hosts:
      - host.docker.internal:host-gateway

  php-web:
    container_name: php-web
    build:
      context: ..
      dockerfile: docker/php/Dockerfile

    env_file:
      - mariadb/envVars.public
      - elasticsearch/envVars.public
      - php/envVars.public

    ports:
      - "9000:9000"

    stdin_open: true
    tty: true

    volumes:
      - ..:/var/www

    extra_hosts:
      - host.docker.internal:host-gateway

    secrets:
      - app_secrets

    entrypoint: ["/usr/local/bin/entrypoint-web.sh"]

  php-worker:
    container_name: php-worker
    build:
      context: ..
      dockerfile: docker/php/Dockerfile

    env_file:
      - mariadb/envVars.public
      - elasticsearch/envVars.public
      - php/envVars.public

    stdin_open: true
    tty: true

    volumes:
      - ..:/var/www

    healthcheck:
      test: ["CMD", "pgrep", "-f", "php bin/console messenger:consume rabbitmq"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    extra_hosts:
      - host.docker.internal:host-gateway

    secrets:
      - app_secrets

    entrypoint: ["/usr/local/bin/entrypoint-worker.sh"]

    depends_on:
      php-web:
        condition: service_healthy

  mariadb:
    container_name: db
    build:
      context: mariadb
      dockerfile: Dockerfile

    env_file:
      - mariadb/envVars.public

    ports:
      - "3380:3306"

    stdin_open: true
    tty: true

    volumes:
      - mariadb-data:/var/lib/mariadb

    secrets:
      - mariadb_password
      - mariadb_root_password

    environment:
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password

  elasticsearch:
    container_name: elasticsearch

    image: elasticsearch:9.0.3

    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

    ports:
      - "9200:9200"
      - "9300:9300"

    stdin_open: true
    tty: true

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  rabbitmq:
    container_name: rabbitmq

    hostname: rabbitmq

    image: rabbitmq:4.1.2-management

    ports:
      - "5672:5672"
      - "15672:15672"

    stdin_open: true
    tty: true

volumes:
  elasticsearch-data:
  mariadb-data:

secrets:
  app_secrets:
    file: php/appEnvVars.private
  mariadb_password:
    file: mariadb/mariadb_password_file.private
  mariadb_root_password:
    file: mariadb/mariadb_root_password_file.private
  elasticsearch_password:
    file: elasticsearch/elasticsearch_password_file.private
